### ISSUE TITLE
define standard LTI role URIs

### ISSUE THREAD

**Issue by lsloan** [dmitry-viskov/pylti1.3#22] opened 2020-08-04 15:24 UTC
It would be very helpful if this module had symbols defined for the URIs of the standard user roles.  Symbols for various other URIs commonly used in LTI support would be helpful, too.

**Comment by dmitry-viskov** [comment] 2020-09-22 09:50
hi @lsloan 
https://github.com/dmitry-viskov/pylti1.3#check-users-role-after-lti-launch
does this change cover your needs or you would like to add something else?

**Comment by lsloan** [comment] 2020-10-19 20:33
Yes, it probably would help. My colleague used v1.7.0 of your module to add LTI support to our application.  I see you added that in v1.8.0.  We're currently using checks we've written to search the roles for things like…

```python
INSTRUCTOR = 'http://purl.imsglobal.org/vocab/lis/v2/membership#Instructor'
TA = 'http://purl.imsglobal.org/vocab/lis/v2/membership/Instructor#TeachingAssistant'
```

Probably if we upgrade to the latest version of your module, we can simplify our code.

**Comment by dmitry-viskov** [comment] 2020-11-17 15:58
hi @lsloan . I'll close this issue because seems that the problem is resolved. But PRs are welcome in case of lack something.

**Closed by dmitry-viskov** 2020-11-17 15:58 UTC
